name: Smoke Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          push: false
          load: true
          tags: exercism/php-test-runner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
