name: Test JUnit-to-JSON

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Update NPM
        run: |
          npm install -g npm@7.5.4

      - name: Build junit-to-json
        run: |
          cd junit-to-json && npm install

      - name: Jest tests
        run: |
          cd junit-to-json && npm run test
